### ISSUE TITLE
[doc] 서버통신 할 url(user)

### ISSUE THREAD

**Issue by kimhanui** [MeeatNow/MeeatNow#11]
## 공통
- 모든 데이터는 json으로 유지하며 송수신 할때만 string으로 바꿈.
- json명세는 도메인(user, loby, location) 별 가장 아래에 있음.
- 서버포트는 8080 으로 개발 -> `localhost:8080`으로 시작하면된다.
- 특별한 경우를 제외하고 url패턴은 `/(도메인)/(행위)`이다 
    > /user/insert 는 유저를 추가한다.
## 유저(User)

**1. insert**: [post]  `/user/insert` + request json (아래 참고)

**2. update**: [post]  `/user/update/숫자` + request json
> ex) `/user/update/2`

**3. find**: [get] `/user/find/숫자`

**4. findAll**: [get]  `/user/findAll`

**5. delete**: [post]  `/user/delete/숫자`

※ request json 명세( 안드 -> 서버 )
```
명세
String email  -> string형은 " " 안에 값 넣어주면 된다.
String name

ex)
{
 "email":"2kw@n",
 "name":"yhhun"
}
```

## ~로비(Loby)~ 아직 참고X

**1. insert**: [post] `/loby/insert` + request json

**2. update**: [post] `/loby/update/숫자` + request json
> ex) `/loby/update/2`

**3. find**: [get] `/loby/find/숫자`

**4. findAll**: [get] `/loby/findAll`

**5. delete**: [post] `/loby/delete/숫자`

※ request json 명세( 안드 -> 서버 )
```
String title;
String hostName;
String openLink;
Location location; -> latitude, longitude으로 값 채워준다. (ex참고)
LocalDate meetingDate; -> 패턴 : yyyy-MM-dd (ex참고)

ex)
{
    "title": "chicken party",
    "hostName": "kim",
    "openLink": "openchat//-1",
    "locationDto": {
        "latitude": 38,
        "longitude": 127
    },
    "meetingDate": "2020-03-05"
}
```

**Comment by kimhanui** [comment]
pr올릴 때마다 더 추가하겠습니돠
@jkey20  이따 갱은이가 pr확인해줄거라 내일부터 user 관리 테스트 가능할듯

**Comment by dev210202** [comment]
@kimhanui 확인했습니다 테스트는 현재 Java로 짜여진 파일을 Kotlin으로 모두 변환한 뒤에 테스트할 예정인데 변환하는 속도가 안나면 Java로 테스트해볼게요 수고하셨습니다
